Develop
simsab-ufcg/PrometheeExperiments pull request #2
Opened 2018-09-25 17:46 UTC by Matheus7OP

2018-09-25 17:51 UTC, FMota0 approved these changes

2018-09-25 18:31 UTC, thiagomanel requested changes

2018-09-25 18:31 UTC, thiagomanel commented on experiments/datasetsizes/setup
> +
@Matheus7OP remember, if you run `cd` you need to `cd` back

2018-09-25 18:31 UTC, thiagomanel commented on experiments/warmup0/run
> +cd $code_path/$umbu_caja_path
why running `cd` here? wouldn't $code_path/$umbu_caja_path/run be the same

2018-09-25 18:31 UTC, thiagomanel commented on experiments/warmup0/run
> +ps -ef | grep ./collect | awk '{print $2}' | xargs -n 1 -P 4 kill -9
add a comment to explain what linha 17 does

2018-09-25 18:31 UTC, thiagomanel commented on experiments/warmup0/run
> +
it seems there is no need to `cd` here. why no calling using complete path

2018-09-25 18:31 UTC, thiagomanel commented on experiments/warmup0/setup
> +
avoid `cd`. Why not check the code out in the current directory then `mv` it after

2018-09-25 18:31 UTC, thiagomanel commented on experiments/warmup0/setup
> +if [ ! -e $code_path/$umbu_caja_path/$tiff_name ]; then
it seems this `cd` could be avoided

2018-10-02 17:40 UTC, thiagomanel requested changes

2018-10-02 17:40 UTC, thiagomanel commented on experiments/datasetsizes/setup
> +	if [ ! -e $code_path/$umbu_caja_path/${test_cases[i]}.tif ]; then
uhm ... it could be simpler if you compile outside the loop (also, there is no need to remove the bin in the loop, why no keeping it instaled)

2018-10-02 17:40 UTC, thiagomanel commented on experiments/datasetsizes/setup
> +	if [ ! -e $code_path/$umbu_caja_path/${test_cases[i]}.tif ]; then
... why not using a makefile?

2018-10-02 17:40 UTC, thiagomanel commented on experiments/datasetsizes/setup
> +
make?

2018-10-02 17:40 UTC, thiagomanel commented on experiments/datasetsizes/setup
> +		./$code_path/$tiff_utils_path/tifGenerator ${tiff_sizes[i]} ${test_cases[i]}.tif -R
at first glance, $code_path reads better than ./$code_path (if you agree change every code line using ./$

2018-10-02 17:40 UTC, thiagomanel commented on experiments/datasetsizes/run
> +
can't we remove this `cd`?

2018-10-02 17:40 UTC, thiagomanel commented on experiments/warmup0/setup
> +
avoid direct compilation, move this to a makefile

2018-10-02 17:40 UTC, thiagomanel commented on experiments/warmup1/setup
> +
avoid direct compilation

2018-10-02 20:00 UTC, thiagomanel requested changes

2018-10-02 20:00 UTC, thiagomanel commented on experiments/datasetsizes/setup
> +		./$code_path/$tiff_utils_path/tifGenerator ${tiff_sizes[i]} ${test_cases[i]}.tif -R
you're right, please, ignore the comment

2018-10-02 20:00 UTC, thiagomanel commented on experiments/warmup0/Makefile
> +
doesn't below programs (umbu, tiff, merge) have their own Makefiles?

2018-10-03 11:58 UTC, thiagomanel approved these changes
I'm going to approve this to solve the last cd problem latter.

2018-10-03 11:58 UTC, merged